### ISSUE TITLE
Turn off symbols and heading's ref by default

### ISSUE THREAD

**Issue by Estamin** [Sinacs/Joplin.Plugin.ReMoods.Theme#1]
Hi,
I think that there is an issue with underlined words, as shown in the image below :

![image](https://user-images.githubusercontent.com/66172934/193416177-d26a4679-b60e-403e-b528-faa418d1291e.png)

The `++` symbols are not supposed to be displayed like this, right ?

Thant you for this great theme !

**Comment by Sinacs** [comment]
Umm... That symbol was born to look like this (a round corner square with dbl plus), my purpose is to emphasize the start point of inserted text and strikethrough text.

But please let me get a bit deeper understanding of your point, what exactly made you feel weird? And what would you expect it to look like? Or you can just let me know if you have your own idea.

Or, you are using the inserted text as an underline text, so that made you feel weird?

**Comment by Estamin** [comment]
I just expected my text to be underlined, without any extra information, symbol, or distraction, to help me to stay focused  ; that's how Joplin behave, by default, and it should be kept this way in my opinion.

![image](https://user-images.githubusercontent.com/66172934/193419124-775ef012-8333-4939-91e0-27960e2d7e2f.png)

That's why I felt weird... but maybe that's just me and I will get used to it.

I noticed that the same thing happen with titles H1, H2, H3 etc., but not with **bold** text. I think that consistency would be good here, or even better : choice should be given to user to switch on and off this setting, if possible.

![image](https://user-images.githubusercontent.com/66172934/193419501-86ed2490-e64a-48d1-a1ef-df799f772f58.png)

**Comment by Sinacs** [comment]
Ok, I understand now, thanks for the explanation! And ya, you can turn them off by going the `tools` > `options` > `ReMoods Theme` settings page.

About the heading reference, they are just for reference, making it smaller is the purpose to avoid misunderstanding it as part of the heading.

And sure, they are all already available to be switched, just play around the setting page for the theme.

After listening to your advice, I think I would be considering setting them to default turn-off in the next coming version.

**Comment by Estamin** [comment]
Indeed, here it is :
![image](https://user-images.githubusercontent.com/66172934/193420631-22672df1-f7a4-41fa-9b21-56d1d1920b9a.png)
 It was simple as that. I should have checked that before opening this issue I guess... 🙄 I see that you added the "good first issue" label. Don't you want me to close the issue ?

Concerning the heading references, I got your point. I will give it a try.

**Comment by Sinacs** [comment]
You don't have to close this issue, I've linked it to my task list, and I will target to turn off those things by default. Thanks for the feedback!

**Comment by Sinacs** [comment]
In the new released([v1.0.16](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/releases/tag/v1.0.16)), those symbols are defaulted to turn off now, and there are two more new settings properties that I think you would be interested in:

![image](https://user-images.githubusercontent.com/110529913/193923238-6fc3c324-a09d-484d-9689-70e910d38d58.png)

Thanks, @Estamin! Have a good day!

**Comment by Estamin** [comment]
Great ! Thank you for the tips. I will check this out :)
Have a good day, and thanks again for this awesome theme !
