### ISSUE TITLE
Feature Request: Modernize Notebook Expand Icon

### ISSUE THREAD

**Issue by ScriptInfra** [Sinacs/Joplin.Plugin.ReMoods.Theme#11]
Could we please modernize the notebook expand arrow? I got this idea from the macOS theme which uses the below icon. Maybe we can simply copy that UI?

![image](https://user-images.githubusercontent.com/63025323/196219913-2acfcf97-85e7-4aea-8fa4-0f5c9a5d7d16.png)

In the interest of user choice, my suggestion would be to make the modern/updated notebook expand icon the default, and then allow a setting to disable the updated icon if the user would like to revert back to the default.

**Comment by Sinacs** [comment]
I think I won't consider adding any UI elements at the moment, but I'll keep that in mind. I'm now more focused on fixing bugs and implementing the theme modes.

**Comment by ScriptInfra** [comment]
Thanks! I look forward to any updates!

**Comment by Sinacs** [comment]
Since Joplin v2.9.12 the folder icon is already appearing in front of every notebook title. In ReMoods v3.4.1 updates, I added colors to the folder icon for identifying different levels of the subdirectory, and also implemented the feature to hide the folder icon.

So, I decided to close this issue. And thank you again for sharing your ideas with me!

**Comment by ScriptInfra** [comment]
Thank you for the continued work on this project! Do you think we could re-open this bug at this time? I've added below a screenshot of what is seen using the latest version of the Joplin app and theme:

![Test](https://user-images.githubusercontent.com/63025323/217737127-34bf534a-471c-43a0-8ff6-e1493447552e.png)

Unfortunately we still have the older style "expand arrows" which look quite dated.

**Comment by Sinacs** [comment]
That's fine, this is already in my head, you don't have to reopen this issue.

Currently, I'm focusing on improving the theme modes and all the eye-health-related issues. UI would be the last consideration in the queue.
