### ISSUE TITLE
Solid Line No Longer Visible

### ISSUE THREAD

**Issue by ScriptInfra** [Sinacs/Joplin.Plugin.ReMoods.Theme#12]
Tested on Joplin versions 2.8.8 and 2.9.17 on macOS.

The horizontal line no longer shows as seen below when the solid line option is enabled:

<img width="746" alt="Screenshot 2022-11-29 at 12 58 21 PM" src="https://user-images.githubusercontent.com/63025323/204614992-91a12a3e-0c02-4592-8e7f-90749a6d8724.png">

**Comment by Sinacs** [comment]
This has been fixed in the [v3.4.5](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/releases/tag/v3.4.5) released!

Thank you again for your helpful report!

**Comment by ScriptInfra** [comment]
Looks good on my end as well. Thanks so much!
