### ISSUE TITLE
Search Result Button Clipped

### ISSUE THREAD

**Issue by ScriptInfra** [Sinacs/Joplin.Plugin.ReMoods.Theme#13]
As can be seen in the below screenshots, with the theme applied, the "In:Test" button is clipped at the bottom compared to Joplin without any theme applied:

![Screenshot 2022-12-01 at 10 13 06 AM](https://user-images.githubusercontent.com/63025323/205101194-f7ae7157-92c8-42a9-a172-c15d91dddf58.png)

![Screenshot 2022-12-01 at 10 10 10 AM](https://user-images.githubusercontent.com/63025323/205101221-d983eec0-eec9-4a00-bd27-fa7bd7a46c36.png)

**Comment by Sinacs** [comment]
This has been fixed in the [v3.4.5](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/releases/tag/v3.4.5) released!

Thank you again for your helpful report!

**Comment by ScriptInfra** [comment]
Looks good on my end as well. Thanks so much!
