### ISSUE TITLE
Feature Request: Modernize Notebooks, All Notes, and Tags Icons

### ISSUE THREAD

**Issue by ScriptInfra** [Sinacs/Joplin.Plugin.ReMoods.Theme#22]
In my humble opinion, the Notebooks, All Notes, and Tags Icons look many years dated and do not match the modern look of the theme. I feel this is a large detraction from the look and feel of the app. My current thought is to:

1. Add an option to remove/hide the icons, and leave the wording.
2. Modernize the icons.

I've included below a comparison screenshot of the remoods theme and the macos theme, from which I got this inspiration:

<img width="247" alt="Screenshot 2022-12-06 at 1 13 47 PM" src="https://user-images.githubusercontent.com/63025323/205989667-bb443ddc-12e5-4d9b-b49b-b1e5bbc40003.png">

<img width="247" alt="Screenshot 2022-12-06 at 1 15 16 PM" src="https://user-images.githubusercontent.com/63025323/205989872-1bc3879f-42f8-471b-ab08-7b7ccf44ea2d.png">

**Comment by Sinacs** [comment]
Ok, great! I agree with your point, I was a bit tired for those icons too, and will go for the first choice for now.

I will add an option and set default to "hide", and it will affecting the icon of notebooks, all notes, and tags.

Thank you for the suggestion!

**Comment by Sinacs** [comment]
I had a problem with implementing the feature to hide/show those icons, it doesn't work as I expected. So, I finally decided to remove those icons and not supply the option to turn them back.

**Comment by ScriptInfra** [comment]
Looking forward to the next release!

**Comment by Sinacs** [comment]
Icons are removed in [v3.5.0](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/releases/tag/v3.5.0)
