### ISSUE TITLE
Emoji Partially Truncated

### ISSUE THREAD

**Issue by ScriptInfra** [Sinacs/Joplin.Plugin.ReMoods.Theme#23]
Joplin v2.9.17 (latest)
Remoods v3.4.6

Hello! It appears some of the emojis do not fully fit in the latest version of Joplin:

Working emoji:

![image](https://user-images.githubusercontent.com/63025323/208136933-c3f68fa9-645f-4dce-9617-5d2d6fe1d3ad.png)

Emoji that is cut off at the beginning of the image:

![image](https://user-images.githubusercontent.com/63025323/208137102-b3301caf-3c0b-44cf-be7c-f3fda75e6863.png)

**Comment by Sinacs** [comment]
![Screenshot 2022-12-17 160202](https://user-images.githubusercontent.com/110529913/208232280-cf71c980-d68d-49e5-b1a2-1b54f659e582.png)
This problem has fixed in [v3.5.0](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/releases/tag/v3.5.0)

**Comment by ScriptInfra** [comment]
Looks good on my end, too!
