### ISSUE TITLE
Animate folding/unfolding notebooks

### ISSUE THREAD

**Issue by alexanderadam** [Sinacs/Joplin.Plugin.ReMoods.Theme#24]
**Is your feature request related to a problem? Please describe.**
It would just be a nice thing.

**Describe the solution you'd like**

Something smoother.

Maybe like [this](https://codepen.io/amycheng/pen/NWXOGR), [this](https://codepen.io/lomojean/pen/XWNNyx) or [this](https://tympanus.net/Development/PFold/)?

**PS:** Also smoothly fading in/out the note numbers when they change, would be nice.
**PPS:** Also animating the scrollbar smoothly on hovering scollable elements :wink: 
**PPPS:** Thank you so much for ReMoods!
**PPPPS:** Is there any chance that this theme could be added to the Joplin core one day, so that it would also be available on mobile devices?

**Comment by Sinacs** [comment]
>Animate folding/unfolding notebooks

Umm... I'm not so sure I'm understanding your expectations. Where exactly do you want me to implement the fading effect? Do you mean the Notebook Panel and Note List Panel?

>Maybe like [this](https://codepen.io/amycheng/pen/NWXOGR), [this](https://codepen.io/lomojean/pen/XWNNyx) or [this](https://tympanus.net/Development/PFold/)?

Actually, I think I wouldn't create any complex animations on Joplin UI because it will make ReMoods hard to maintain. While I understand a beautiful outlook can make us feel great, it's hard to implement the main program UI designs using a plugin. Anyway, I will still consider your point "Something smoother" for some current effects.

>Is there any chance that this theme could be added to the Joplin core one day, so that it would also be available on mobile devices?

Wow! I don't know, never thought about this before. Is it possible? :)

Nice to hear from you and thanks for supporting ReMoods!

**Comment by alexanderadam** [comment]
> Do you mean the Notebook Panel and Note List Panel?

Yes, exactly

> I will still consider your point "Something smoother" for some current effects.

That would be perfect. I guess at least scrollbar widths would be easier at least. Fading in/out the note numbers or the list items can probably be difficult depending on how it is implemented on the JS side, I guess.

> Wow! I don't know, never thought about this before. Is it possible? :)

Well, [Joplin has a themes directory](https://github.com/laurent22/joplin/tree/dev/packages/lib/themes).

The existing themes are rather simple, so their files are tinier as well. But maybe Laurent would consider merging it when he sees your theme.

**Comment by alexanderadam** [comment]
Would it be possible to animate the arrow toggle?

**Comment by Sinacs** [comment]
Yes, I have planned to do something for the arrow toggle.

**Comment by Sinacs** [comment]
In conclusion all the above:

1. I will keep your point ”something smoother” in mind and try to turn all visual effects smoother in the future.

2. About the complex UI animations such as the topic of this issue post would not be considered momentarily.

4. Arrow toggle would be implemented in the future.

5. Currently, ReMoods is focusing on improving the theme modes, and most care about the issues of eyes-health. So, the requests that are not directly related to ”eyes-health", would be labeled as "future considerations” and without a guaranteed date.

**Comment by Sinacs** [comment]
The [ReMoods Theme v4.1.4 updates](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/releases/tag/v4.1.4) have solved this issue, thank you!
