### ISSUE TITLE
Contrast bug Copy Code Blocks plugin

### ISSUE THREAD

**Issue by alexanderadam** [Sinacs/Joplin.Plugin.ReMoods.Theme#25]
**Is your feature request related to a problem? Please describe.**

I know, it's an external plugin, but the [Copy Code Plugin](https://github.com/LightAPIs/joplin-copy-code-blocks) can be very handy.
The copy symbol has a very bad contrast with ReMoods though and maybe it's easily fixable? :pleading_face:

**Comment by Sinacs** [comment]
Thank you for telling me this, I will give a test on it! :)

**Comment by alexanderadam** [comment]
Wow, you are _fast_! :heart_eyes:

**Comment by Sinacs** [comment]
I've just taken a look at this plugin and found that it's not within the Joplin plugins repo, but there is another similar plugin with the same feature, and it looks a bit better. ([Code Clipboard](https://github.com/bluulo/joplin-plugin-code-clipboard)) So, I will go for this one and will see it in the next release.

**Comment by Sinacs** [comment]
This issue has been fixed in ReMoods [v4.1.1 updates](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/releases/tag/v4.1.1).

Please let me know if there are any other problems and thank you for supporting ReMoods!
