### ISSUE TITLE
Move formatting controls into floating box

### ISSUE THREAD

**Issue by alexanderadam** [Sinacs/Joplin.Plugin.ReMoods.Theme#27]
Maybe something like Notion

![grafik](https://user-images.githubusercontent.com/372620/217657776-e6c6f609-ec6b-467b-8945-db7b0a023879.png)

I'm sure this would be difficult but I guess asking won't hurt, right? :pleading_face:

**Comment by Sinacs** [comment]
Do you mean to make it stay close to the typing text?

**Comment by Sinacs** [comment]
Haha, that's a good idea, but this request seems more suitable for posting on Joplin Repo. 

I don't want to reject any improvement requests from ReMoods but unfortunately, this one wouldn't be considered. And I'm gonna close this issue.
