### ISSUE TITLE
Note title contrast is sometimes low [BUG]

### ISSUE THREAD

**Issue by alexanderadam** [Sinacs/Joplin.Plugin.ReMoods.Theme#29]
The selected one is good but the following are black on dark green

![grafik](https://user-images.githubusercontent.com/372620/217660584-a8e0b650-c999-4ec3-9e24-359ae5a9664a.png)

**Comment by Sinacs** [comment]
Great! Noted.

**Comment by Sinacs** [comment]
This issue has been fixed in ReMoods [v4.1.1 updates](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/releases/tag/v4.1.1).

Please let me know if there are any other problems and thank you for supporting ReMoods!

**Comment by alexanderadam** [comment]
Perfect, thank you!
