### ISSUE TITLE
Add option to change the code block border style (solid <=> dotted) 

### ISSUE THREAD

**Issue by Sinacs** [Sinacs/Joplin.Plugin.ReMoods.Theme#3]
https://discourse.joplinapp.org/t/plugin-remoods-theme/27547/34?u=sinacs

**Comment by Sinacs** [comment]
Solved: https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/releases/tag/v2.0.0

**Comment by ScriptInfra** [comment]
Confirmed this works on my end as well. Thanks so much!

**Comment by Sinacs** [comment]
Yay! Thanks for your help! Leave me a message if you found any other issues!
