### ISSUE TITLE
Background color for `==XXXX==` is missing [BUG]

### ISSUE THREAD

**Issue by SeptemberHX** [Sinacs/Joplin.Plugin.ReMoods.Theme#31]
**Describe the bug**

`==XXX==` is not highlighted in markdown editor anymore.

**To Reproduce**

It happens to every `==XXX==`.

With the Dev tools, the background color is set to `--me-mark-bg`, but the variable `--me-mark-bg` is not found. I found `--me-mark-bd` instead.

**Expected behavior**

`==XXX==` should be highlighted in markdown editor.

**Screenshots**

**Desktop**
 - OS: macOS Big Sur 11.3
 - Joplin version: 2.10.4
 
**Additional context**

**Comment by Sinacs** [comment]
Thx @SeptemberHX, it will be fixed.

**Comment by Sinacs** [comment]
This issue has been fixed in ReMoods [v4.1.1 updates](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/releases/tag/v4.1.1).

Please let me know if there are any other problems and thank you for supporting ReMoods!
