### ISSUE TITLE
Option to choose/change the style of inline code

### ISSUE THREAD

**Issue by seth100** [Sinacs/Joplin.Plugin.ReMoods.Theme#32]
## Is your suggestion related to a problem? Please describe.

No

## Describe the solution you'd like:

It would be nice to have an option to choose the style of the inline code.
So that I can choose to use the current one having `>|` (which is a bit confusing for me) or another one, and it would be the best to have another style not having the prepending `>|`.
Is that possible?

Thanks

**Comment by Sinacs** [comment]
Hello there, ReMoods has already supplied the settings property to do that.

Please go to `tools` > `Options` > `ReMoods Theme`, and then scroll down to have a look:

![Screenshot 2023-02-17 164156](https://user-images.githubusercontent.com/110529913/219596497-e2dfed23-f4b8-4dc4-be64-dd306b48824a.png)

Thanks for supporting ReMoods Theme, and you are welcome to leave me a message anytime!

**Comment by seth100** [comment]
oh thank you so much, I just missed that option! Thanks
