### ISSUE TITLE
Enabling this theme extension will cause the following issues: Please see a detailed demo:

### ISSUE THREAD

**Issue by zhouxinghong** [Sinacs/Joplin.Plugin.ReMoods.Theme#36]
Enabling this ReMoods Theme extension will cause the following issues:
Please see a detailed demo:
https://github.com/laurent22/joplin/issues/7864

**Comment by Sinacs** [comment]
Good day!

Umm... I think I've missed something, what's happened in the last two hours? :)

Thank you for the report even it seems you've solved the problem by yourself.

Feel free to leave me a message again if there is any I can help!
