### ISSUE TITLE
Static KaTeX Math Option

### ISSUE THREAD

**Issue by athai-009** [Sinacs/Joplin.Plugin.ReMoods.Theme#40]
## Is your suggestion related to a problem? Please describe.

I don't like that math in KaTeX shrinks and grows. I looked for an option to disable that feature, but I did not find one.

## Describe the solution you'd like:

It would be great if an option to disable dynamic font size with KaTeX outputs.

**Comment by Sinacs** [comment]
Ok, it will be included in the upcoming updates, and thank you for supporting ReMoods!

**Comment by athai-009** [comment]
Thank you!
