### ISSUE TITLE
it is indistinguishable when select inline code or code block,

### ISSUE THREAD

**Issue by jabari-12** [Sinacs/Joplin.Plugin.ReMoods.Theme#47]
## Environment:

 - OS: Ubuntu22.04
 - Joplin version: 2.8.8
 - ReMoods theme version: V4.3.2
 - ReMoods Theme Mode: Dusk Mode

## Describe the bug:
When I select the code, I can't tell from the color whether it's selected or not。

## Screenshots:

I select the whole code block, but its background color is still black, so it is difficult to judge whether it's selected or not。
![image](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/23380844/d6f16ed9-7bd3-489c-8431-572d917ad0df)

**Comment by Sinacs** [comment]
Hi @jabari-12, I've tested in serval Joplin versions, and it works fine on v2.8.8 too. But I found that this issue should be related to the lack of support for the Rich markdown plugin. Please make sure you have already installed the Rich Markdown plugin when you are using ReMoods Theme. 

For more details please visited: https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/blob/master/Doc-GettingStartedGuide.md

Please let me know If it doesn't solve your problem and thank you for supporting ReMoods Theme! 😃

**Comment by jabari-12** [comment]
@Sinacs  Yes, It works for me when I installed the Rich markdown plugin. 
Thank you very much!
