### ISSUE TITLE
Remoods does not honor the new "New note" and "New to-do" buttons.

### ISSUE THREAD

**Issue by ScriptInfra** [Sinacs/Joplin.Plugin.ReMoods.Theme#48]
The latest v4.3.2 Remoods theme does not honor the new Note and To-Do buttons in Joplin v2.11.4. My suggestion would be to allow the user to disable the new "New note" and "New to-do" buttons with a settings in the Remoods theme. I prefer the new larger buttons, however some users have expressed the contrary on the Joplin discourse.

Theme applied:
![image](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/63025323/df44713b-88a4-4dac-ba93-9fd3c947d5ad)

No theme applied:
![image](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/63025323/623d844b-b014-43d8-a0eb-f763c42e237d)

**Comment by Sinacs** [comment]
This issue has been fixed in [ReMoods Theme v4.4.0](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/releases/tag/v4.4.0).

**Comment by ScriptInfra** [comment]
Hi @Sinacs! Thanks for the update. I am seeing some strange behavior here.


Below is a screenshot of Joplin without Remoods applied which shows the new 'New note' and 'New to-do' buttons:

<img width="729" alt="Screenshot 2023-06-05 at 3 22 50 PM" src="https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/63025323/0ef2caa1-fdd1-4566-846f-ea6d2d52d9da">

However the below screenshot with the Remoods theme applied shows the old buttons:

<img width="735" alt="Screenshot 2023-06-05 at 3 25 34 PM" src="https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/63025323/71255965-d26c-499e-8d43-48a2f850538f">


This behavior only occurs when you stretch the note list out quite far as seen in the screenshots. But, I was wondering if there is any way to fix this?

**Comment by Sinacs** [comment]
I can't recreate the problem on my side. Please make sure you are already disabled the newly launched feature `Note List Panel - Enable smaller "New Note" & "New Todo" button` and click `OK` then restart Joplin.

I didn't have any problem in any width:
![Screenshot 2023-06-06 041619](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/110529913/43e671c1-a8cb-4006-b6c7-1f3d0731f8e0)

**Comment by ScriptInfra** [comment]
Yes, that was the problem! I think I see why I was confused. On the second line (screenshot below), it reads 'Enable: Bigger button'. Thus I had the button enabled which actually enables the smaller button. Is this just a typo or am I misunderstanding the language? Thanks so much!

<img width="750" alt="Screenshot 2023-06-05 at 9 45 49 PM" src="https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/63025323/e943b679-3f74-4f40-a32e-655f57ad4a3a">

**Comment by Sinacs** [comment]
OMG! You're right! I'm so sorry about the wrong description for the setting. Thank you for pointing it out, and would be fix it as soon as possible.
