### ISSUE TITLE
Inline KaTeX does not render as expected.

### ISSUE THREAD

**Issue by JHTNT** [Sinacs/Joplin.Plugin.ReMoods.Theme#53]
## Environment:

 - OS: Windows 10 21H2
 - Joplin version: 2.10.19
 - ReMoods theme version: v4.4.0

## Describe the bug:

When I use inline KaTeX on the original Joplin, it looks fine.

![image](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/22848048/2a69852b-03bc-48c2-89ef-0b7565cf6fd5)

But when I'm using ReMoods Theme, it looks so weird. The style of numbers and symbols is the same as the plain text.

![image](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/22848048/2d80dfb3-ace4-4f48-87a1-8af179f12357)

## Expected behavior:

I think the inline KaTeX should be rendered like the original Joplin.

**Comment by Sinacs** [comment]
Ok, great! It will be fixed in the next update, thanks for the report!

**Comment by Sinacs** [comment]
Hi @JHTNT ! The [ReMoods Theme v4.5.0 updates](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/releases/tag/v4.5.0) has found and fixed serval issues that related to the katex and math notation, I hope they are working well for you! Please let me know if there are any other problems you find! 🥂

- Sinacs
