### ISSUE TITLE
The left border of the Admonition plugin is not showing well.

### ISSUE THREAD

**Issue by JHTNT** [Sinacs/Joplin.Plugin.ReMoods.Theme#54]
##  Plugin Name:

[Admonition markdown extension](https://github.com/maxnegro/joplin-plugin-admonition)

## Describe the problems:

The top of the left border is outside the box.

![image](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/22848048/acfb855f-c57a-493c-b2ed-5d3e38f5ab5e)

## Describe your expectations:

The height of the left border should fit in with the top of the box.

![image](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/22848048/77611ace-4b8e-40b3-8fcd-c585bbd9fd66)

**Comment by Sinacs** [comment]
Ok, got it! It will be fixed in the next update, thank you @JHTNT !

**Comment by Sinacs** [comment]
This issue has been fixed in the [ReMoods Theme v4.5.0 updates](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/releases/tag/v4.5.0).
