### ISSUE TITLE
Ask for help [non-bugs]

### ISSUE THREAD

**Issue by zhouxinghong** [Sinacs/Joplin.Plugin.ReMoods.Theme#55]
question:
1. How to delete the newly created notebook in Joplin 2.11.9?
2. How to delete the newly created subnotebook in Joplin 2.11.9?
Can you tell me if you know how? Thank you very much!
Windows10

**Comment by Sinacs** [comment]
Whatever situations you've created a notebook, subnotebook, note, or tag, you just need to right click the target element and select `Delete`, It will work perfectly fine. See below:

![Screenshot 2023-06-16 093520](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/110529913/7577327a-1aec-4b47-9114-c9b69a7a389e)

P.S. I'm using Win11 but I think it's just the same.

**Comment by Sinacs** [comment]
Additionally, if it's not working for you, please try to go to `Help` > `Toggle safe mode` and it will restart Joplin in the naked mode, then try again to create & remove folder. It's just to make sure if the problem is caused by any other plugins you've installed.

**Comment by zhouxinghong** [comment]
Thank you very much for your sincere answer 😜👍👏🎉, what is your jopin version?
One more question, how did you remove unreferenced note attachments, eg: image resources etc

**Comment by zhouxinghong** [comment]
My end goal is to want to delete those old notebook folders. However, a notebook folder is never displayed in jopin's resource manager. This design idea is very confusing.

**Comment by zhouxinghong** [comment]
I'll try your way next time. Because I just uninstalled joplin again.😂

**Comment by Sinacs** [comment]
1. I'm using Joplin v2.11.19.
2. When you've created any attachments within your notes, Joplin will generate the resources in the standalone `resources` folder for the specific `profile`. You can just visit that folder by going to `Help` > `Open Profile Directory`.
3. I'm not so sure what exactly your situation is about the old notebook not showing up.

**Comment by Sinacs** [comment]
It's fine, but even if you have uninstalled Joplin, your old notes are still in the Joplin's directory.

**Comment by zhouxinghong** [comment]
Um! Yes. 👌
Also the themes you provide are great! It is because of your excellent theme that I reinstall joplin again and again, thank you very much! 😜

**Comment by Sinacs** [comment]
Umm... But "reinstall Joplin again and again" is not the experience ReMoods expected to provide you. 🤣 
Anyway, thank you for loving ReMoods, just feel free to let me know if there is anything I can help with. Cheers 🥂

-Sinacs

**Comment by zhouxinghong** [comment]
no problem! At the same time, I hope your theme will become more and more robust and perfect, and I hope you have a happy work! 🥂
Take the liberty to ask! Are you a Hong Kong compatriot? 😜

**Comment by Sinacs** [comment]
I hope so, and yes, I'm from HK. So, it's welcome to reports in Chinese. BIG HUG! 🤗

**Comment by zhouxinghong** [comment]
Hong Kong has always been a role model for us to learn from👍👍👍😜 We have been deeply infected by the cultural atmosphere of Hong Kong since childhood (Jin Yong TV series, Hong Kong movies, etc.). Most compatriots in Hong Kong are also much more educated than us. I sincerely hope that Hong Kong's tomorrow will be better and better! The compatriots in Hong Kong will become better and better! 👍👍👍😜

**Comment by Sinacs** [comment]
We are both having our good and bad, but all of that just come from our living environment, and it's not necessary to compare which is better. We have to learn from each other not due to who's better, it's just because the word "changes" is always working shadily behind "better". I believe wherever people are born, everything must be better just because they truly work things out together.

I'm happy that you love my home place, and I love China too since I've my job in GZ and SH for 6 years in the past, and it also created a lot of unforgettable memories for me. Whatever, thank you for recalling my happy memories again! Let's grow together and all become better!

**Comment by zhouxinghong** [comment]
ok 👌! Let's grow together! work together! Let's become a valuable person in this society together! 👍😜🥂
