### ISSUE TITLE
Inconsistent background color

### ISSUE THREAD

**Issue by zhouxinghong** [Sinacs/Joplin.Plugin.ReMoods.Theme#56]
Inconsistent background color

The correct performance should be that all background colors should be the background colors provided by the ReMoods theme

## Environment:

 - OS: Windows 10
 - Joplin version: 2.11.9
 - ReMoods theme version: 4.5.0

## Screenshots:

![image](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/54253524/312eca08-3939-479b-9779-5e6083123416)

The correct performance should be that all background colors should be the background colors provided by the ReMoods theme

**Comment by zhouxinghong** [comment]
Therefore! 😂 That's why I turned it off

**Comment by Sinacs** [comment]
You can use the markdown toc features instead of outline plugin.

**Comment by zhouxinghong** [comment]
So how to use markdown toc function? 😂

**Comment by Sinacs** [comment]
You should modify the Joplin built-in settings first, to enable a few markdown features which are turned off by default.

Ref: https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/blob/master/Doc-GettingStartedGuide.md#modify-the-joplins-built-in-settings

And the `Enable table of contents extension (WYSIWYG: no)` is exactly what we are talking about.

After you have enabled it, you can create a new note for testing:

1. Open the Joplin split view
2. Use the markdown editor
3. Create multiple h2 headings
4. And then type the syntax `[[toc]]` on a new line.

And then you will see the TOC button appears at the bottom right of the render viewer. Mouse hovering over that button, and you will see the TOC block comes out.

Like this:

https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme#floating-toc
