### ISSUE TITLE
Inconsistent Folder Colors

### ISSUE THREAD

**Issue by ScriptInfra** [Sinacs/Joplin.Plugin.ReMoods.Theme#57]
Hello! I am wondering if it is a bug that I am seeing multiple different colors for folders:

![image](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/63025323/e5b8c7dd-8b32-479f-af20-ac5f078ac744)

As you can see, there seem to be multiple different colors for the folder icons. I ask because these colors do not seem to follow the "Green -" that I have selected for the hue.

## Environment:

 - OS: Fedora 38
 - Joplin version: 2.12.4
 - ReMoods theme version: 4.5.1

**Comment by Sinacs** [comment]
This is normal; it helps identify the directory's levels, especially when users have lots of folders.

**Comment by ScriptInfra** [comment]
I understand. Would it be possible to add a setting to enable/disable this feature? The inconsistent folder coloration makes it a little confusing on my eyes when working in multiple subfolders.

**Comment by Sinacs** [comment]
No problem :)

**Comment by Sinacs** [comment]
Ok, it finally added in the [v4.6.0](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/releases/tag/v4.6.0)!

**Comment by ScriptInfra** [comment]
@Sinacs - Thank you! Is it possible the setting is flipped? When I check the box for 'Notebook Panel - Enable multiple colors for nested notebook folder', the multi-colors actually disappear. Then when I uncheck the setting, the multi-colors come back.

**Comment by Sinacs** [comment]
@ScriptInfra It's has been solved in the latest v4.6.1 release. Thank you for the reminder! :🍻

**Comment by ScriptInfra** [comment]
@Sinacs - Looks good, thank you so much!
