### ISSUE TITLE
OLED Theme

### ISSUE THREAD

**Issue by Opisek** [Sinacs/Joplin.Plugin.ReMoods.Theme#58]
I am very impressed by this plugin's various features like the floating TOC button and other quality of life changes. However, I do not dig the theme. I would like to keep using this plugin, however I'd prefer for the styling to remain mostly the same.

Could it be possible to add Joplin's default themes as an option or at least some OLED mode (pitch black background) as an alternative to the still very bright Dusk and Night?

**Comment by Sinacs** [comment]
Hi Opisek! Yes, it's possible, I would try to add the pure black background color as an extra option for the night mode but I won't consider developing an extra theme selection at the moment. And, you will see it in the next release as an experimental feature.

**Comment by Sinacs** [comment]
This request has been partially implemented in the [v4.6.0](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/releases/tag/v4.6.0) release, feel free to let me know if there is any problem. Thank you again!

**Comment by Opisek** [comment]
Looks amazing so far! Thanks for the work.
