### ISSUE TITLE
Math Equation Auto-Enlarge can't be turned off

### ISSUE THREAD

**Issue by Opisek** [Sinacs/Joplin.Plugin.ReMoods.Theme#59]
## Environment:

 - OS: Windows 11
 - Joplin version: 2.10.19
 - ReMoods theme version: 4.5.1

## Describe the bug:
The math auto-enlarge effect cannot be turned off fully. Even when' it's off, it still enlarges superscripts.

## To Reproduce:
1. Disable math equation auto-enlarge
2. Restart joplin
3. Type `$a^b$`
4. Hover over the equation
5. The `b` is still enlarged

## Expected behavior:
Nothing should be enlarged

**Comment by Sinacs** [comment]
This issue has been fixed in the [v4.6.0](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/releases/tag/v4.6.0) release. Thank you for supporting ReMoods Theme! 🥂 

-Sinacs

**Comment by Opisek** [comment]
Unfortunately, subscripts and superscripts appear to be permanently zoomed in now. Here are some screenshots that should display the issue:

![image](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/40141286/ab307948-41d1-41dc-9998-6abae8d9597b)
![image](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/40141286/6555795d-ed83-4252-91a5-75a59df56cc7)

**Comment by Sinacs** [comment]
Oh, my bad! I will release a quick fix as soon as possible.

**Comment by Sinacs** [comment]
I've looked deeper into several math notation features and found that the math notation font size settings generated many unexpected problems. So, I finally removed them to make sure it's good for everyone.

In the latest v4.6.1, all math notations in the render viewer should be the same as Joplin defaults(except color):

![Screenshot 2023-07-25 063556](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/110529913/2aa2711d-f907-454c-b289-0741eab73a20)
