### ISSUE TITLE
Style Application Header (Notebooks/Search/Note Name)

### ISSUE THREAD

**Issue by ScriptInfra** [Sinacs/Joplin.Plugin.ReMoods.Theme#7]
Request to kindly update the header to match the UI of the app as discussed here: https://discourse.joplinapp.org/t/plugin-remoods-theme/27547/36

**Comment by Sinacs** [comment]
Solved: https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/releases/tag/v2.0.0
